### ISSUE TITLE
Terrorism Theme

### ISSUE THREAD

**Issue by 101ms-2** [GrimReaper2654/Gacha-Game#11]
I think you should include an map DESIGNATED for terrorism-based characters. Improve lore on Redacted and JAT MQ69-Reaper2.

oTher thAn that Just need more fps!

**Comment by GrimReaper2654** [comment]
factual

**Comment by tvdk-sudoku** [comment]
@101ms-2 Who on earth are you?

**Comment by GrimReaper2654** [comment]
added
